Vagrant.configure("2") do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.hostname = "grup09.fjeclot09.net"


  config.vm.synced_folder "/home/hpkubuntu/Documentos/vagrantmaquina/gp2f4/codi", "/var/www/html"
  config.vm.provider "virtualbox" do |v|
    # v.gui = true
    v.name = "grup09"
    v.memory = 2048
    v.cpus = 2
    v.customize ['modifyvm', :id, '--clipboard', 'bidirectional']
  end

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 443, host: 8443
  config.vm.network "public_network", bridge: "Intel(R) 82579LM Gigabit Network Connection"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update -y
    sudo apt-get upgrade -y
    sudo apt-get install -y net-tools
    sudo apt-get install -y apache2 apache2-doc
    sudo apt-get install -y libapache2-mod-php
    sudo apt-get install -y php7.4
    apt-get install -y mariadb-server mariadb-client
    apt-get install -y php7.4-mysql

    sudo apt update
  sudo apt install -y curl unzip php-curl
  sudo apt install -y curl unzip php7.4-curl
  curl -sS https://getcomposer.org/installer | php
  sudo mv composer.phar /usr/local/bin/composer

  SHELL

end



